kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rbac-example-binding
  namespace: ecodia
subjects:
- kind: User
  name: testuser
  apiGroup: "rbac.authorization.k8s.io"
roleRef:
  kind: Role
  name: rbac-example
  apiGroup: "rbac.authorization.k8s.io"
