apiVersion: v1
kind: Pod
metadata:
  name: rbac-test
  namespace: ecodia
spec:
  containers:
  - name: rbac-test
    image: ubuntu
    command: ["sleep"]
    args: ["infinity"]
  restartPolicy: OnFailure
