apiVersion: v1
kind: Pod
metadata:
  name: multiple-containers
  labels:
    app: multi
spec:
  containers:
  - name: first
    image: ubuntu
    command: ["/bin/bash", "-c", "for i in {1..1000}; do echo $i; sleep 1; done"]
  - name: second
    image: ubuntu
    command: ["/bin/bash", "-c", "for i in {1..1000}; do date; sleep 1; done"]
  initContainers:
  - name: logging-init
    image: ubuntu
    command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
    securityContext:
      privileged: true
